{% set name = "bitsandbytes" %}
{% set version = "0.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Don't use the PyPI source tarball as this already contains compiled code.
  url: https://github.com/TimDettmers/bitsandbytes/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5ca143b533a06bdfe594768ec39c4ad117f8541e2f169f84d376eeec5e6447da

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - pip
  run:
    - python
    - pytorch

test:
  imports:
    - bitsandbytes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/TimDettmers/bitsandbytes
  summary: k-bit optimizers and matrix multiplication routines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
