{% set name = "bitsandbytes" %}
{% set version = "0.43.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Don't use the PyPI source tarball as this already contains compiled code.
  url: https://github.com/TimDettmers/bitsandbytes/archive/refs/tags/{{ version }}.tar.gz
  sha256: 00265aae085a32b001b4fce737ec28c0193df58336ed2c72bbb295aa869f490e

build:
  number: 1
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  skip: true  # [not linux]
  skip: true  # [cuda_compiler_version == "10.2"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler("cuda") }}                 # [cuda_compiler_version != "None"]
    - cmake
    - ninja
  host:
    - python
    - pip
    - cuda-cudart-dev   # [(cuda_compiler_version or "").startswith("12")]
    - libcublas-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev   # [(cuda_compiler_version or "").startswith("12")]
    - cuda-version  {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - scipy
  run:
    - python
    - pytorch
    - scipy

test:
  imports:
    - bitsandbytes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/TimDettmers/bitsandbytes
  summary: k-bit optimizers and matrix multiplication routines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
