{% set name = "bitsandbytes" %}
{% set version = "0.41.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Don't use the PyPI source tarball as this already contains compiled code.
  url: https://github.com/TimDettmers/bitsandbytes/archive/refs/tags/{{ version }}.tar.gz
  sha256: 79f24d75d607c30040ed78b13fc621a488f57462e86aed5667e049f8b346642c

build:
  number: 1
  skip: true  # [not linux]
  skip: true  # [cuda_compiler_version == "10.2"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler("cuda") }}                 # [cuda_compiler_version != "None"]
    - make
  host:
    - python
    - pip
  run:
    - python
    - pytorch
    - scipy

test:
  imports:
    - bitsandbytes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/TimDettmers/bitsandbytes
  summary: k-bit optimizers and matrix multiplication routines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
